version: '3.9'

services:
    notification-service:
        container_name: notification-service
        image: razom-pay/notification-service:dev
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        env_file:
            - .env.production.local
        expose:
            - '9102'
        volumes:
            - ../logs/notification:/var/log/services/notification
        networks:
            - razom-pay

networks:
    razom-pay:
        external: true
